
spring:
  application:
    name: equipment-management
  datasource:
    url: jdbc:postgresql://postgresql.woods.local:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  flyway:
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${APP_SMTP_USER:}
    password: ${APP_SMTP_PASS:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  username: ${APP_USERNAME:admin}
  password: ${APP_PASSWORD:admin}
  smtp-user: ${APP_SMTP_USER:}
  smtp-pass: ${APP_SMTP_PASS:}
  smtp-from: ${APP_SMTP_FROM:"Equipment Management <noreply@example.com>"}
  app-url: ${APP_URL:http://localhost:8080}
  email-recipient: ${APP_EMAIL_RECIPIENT:mr.paul.woods@gmail.com}

scheduling:
  enabled: true
